#!/usr/bin/env bash
# return subdomain, record type, and destination
function dig_it () {
    if [ "$2" ]
    then
        dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{ printf "The subdomain %s is a %s record and points to %s\n", subd, $4, $5 }' subd=$2
    elif [ "$1" ]
    then
        dig_it "$1" "www"
        dig_it "$1" "lb-01"
        dig_it "$1" "web-01"
        dig_it "$1" "web-02"
    fi
}

dig_it $1 $2
