#!/usr/bin/env bash
# install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
sudo touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
