#!/usr/bin/env bash
# install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
