#!/usr/bin/env bash
# install nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo chmod 777 /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sudo chmod 777 /var/www/html/index.html
srvr="^server {$"
add="server {\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
file="/etc/nginx/sites-available/default"
sudo sed -i 's,'"$srvr"','"$add"',' "$file"
sudo service nginx restart
