#!/usr/bin/env bash
# redirect

sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sudo sed -i '36a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
