#!/usr/bin/env bash
# Install nginx on yo web-01 server
# And configures /redirect_me to redirect to another page.
sudo apt-get update
sudo apt-get install -y nginx
sudo touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/server_name _/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
