#!/usr/bin/env bash
# redirect
sudo apt-get update -y
sudo apt-get install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sudo sed -i '36a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i '39a error_page 404 = /custom_404.html;'
sudo service nginx restart
