#!/usr/bin/env bash
# set up load balancer
sudo apt-get update
sudo apt-get -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 1653-web-01 34.75.53.84:80\n\tserver 1653-web-02 3.89.225.162:80\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
