#!/usr/bin/env bash
# This script is displaying status of a file

if test "holbertonschool"
then
	echo "holbertonschool file exists"
	if test -s "holbertonschool"
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	if test -f "holbertonschool"
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
