#!/usr/bin/env bash
# run nginx as nginx
sudo service apache2 stop
sudo pkill apache2
sudo sed -i "1auser nginx;" /etc/nginx/nginx.conf
sudo chmod -R 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
