#!/usr/bin/env bash
# run nginx as nginx
sudo service apache2 stop
sudo pkill apache2
sudo sed -i "1auser nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod -R 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
